### ISSUE TITLE
Support for energy management

### ISSUE THREAD

**Issue by ddcbe** [crownstone/crownstone-home-assistant#6]
The latest release of home-assistant adds new possibilities for energy management. (https://www.home-assistant.io/blog/2021/08/04/home-energy-management/). The crownstones could be used as device monitors. To do that, energy consumption should be reported in kWh. They also should meet the requirements for long-term statistics (https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics). I believe all information is available but needs some small adaption to meet the requirements but would make the crownstones great additions for the energy management (both measuring and switching, ... )

**Comment by RicArch97** [comment]
This will be added in the next version of this integration, which is currently about 75% done I'd say. It has gone through a complete overhaul so it took a little longer. The energy statistics are already added and working.

I'm aiming for a release when Home Assistant version 2021.9 is released as it it based on the code in that.

**Comment by ddcbe** [comment]
That's great news! Looking forward to that release!

**Comment by RicArch97** [comment]
Assuming you are currently using the dongle with energy usage enabled;

Currently the implementation is as follows:
1. The value for energy starts at 0 in HA after you install the integration
2. The value in HA does **not** reset when the Crownstone does. (the Crownstone resets on power loss, reboot, software update)
3. The value in HA resets back to 0 every month

Especially the last point may be questionable as I added that in to get monthly usage, however not everyone may like that. In HA you can also see monthly usage regarding of this reset.

So the questions are: 
1. Do you want the value to reset back to 0 after x time? If not, it will just keep counting forever.
2. Should the value start at 0 in HA? it is also possible to take the exact value from the Crownstone. In that case the energy usage will have started since the moment the Crownstone was last powered on, and the value might be high from the start.
3. Should Crownstone resets be taken into account? This extends point 2, where it matches the value on the Crownstone, but in case the Crownstone resets, the value in HA also resets.

Any feedback will be appreciated!

**Comment by ddcbe** [comment]
Hi,

I'm using the USB dongle with energy usage indeed.

Personally, I prefer the counter going up constantly. I'm mostly interested in delta's like hourly, daily, monthly usage. The reset just makes this more complex. It also doesn't need to start at zero in HA. Again, only delta's have a real meaning. So resetting a crownstone shouldn't reset the value neither. But that is just my opinion. 

Kind regards and thanks for the nice work.

**Comment by RicArch97** [comment]
Thanks for your input!

I had the values start at 0 in HA as I thought the values straight from the Crownstones would be pretty meaningless. For example if you get a value of 150 kWh right after installing it doesn't say that much. I do agree that the delta's are most important. I will change it into an always increasing value.

**Comment by AlexDM0** [comment]
Hi guys, I’d argue that the only relevant information is the deltas. To the point where I’m not sure it’s relevant to show the ever increasing value. This might be fun for developers to see the “raw” measurements but for the “normal” users only the deltas are of value. As pointed out by @ddcbe the different deltas are nice to have at a glance (hourly, daily, weekly, monthly).

The reset is a technical detail an not something we should bother an end user with. In the Crownstone hub we combine the incoming information to make sure the resets do not lose data. @ricArch97 maybe we can discuss this next week?

Regards
________________________________

**Comment by ArthurvdMolen** [comment]
> This will be added in the next version of this integration, which is currently about 75% done I'd say. It has gone through a complete overhaul so it took a little longer. The energy statistics are already added and working.
> 
> I'm aiming for a release when Home Assistant version 2021.9 is released as it it based on the code in that.

Great!!!

**Comment by RicArch97** [comment]
Little status update on the next HACS release of this integration;

I had to stall it because the Crownstone integration submitted to core went through review, and some significant changes were made during that, and I wanted to include those changes in the HACS version as well.

That way the HACS version builds on top of the core integration, with the same base code but with extra (unreviewed) functionality. It will be marked as beta version from now on. 

I will release the beta (HACS) version with all the changes after Home Assistant 2021.10. This is when the official Crownstone integration will also be included. More info on all  the changes will be included with the release notes.

**Comment by ddcbe** [comment]
Thanks, looking forward to it! 
Am I correct that the energy management code will be available in the beta (HACS) branch?

**Comment by RicArch97** [comment]
Yes the energy measurements are beta as that feature is not available yet in the first version of the official integration.
You can just keep using this repository in HACS to keep energy measurement feature.

**Comment by RicArch97** [comment]
Added in release 2.0.0. If there are issues with energy management you may open a new issue.
